# Generated by Django 4.2.18 on 2025-01-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyGeneric', '0002_alter_movimiento_product_alter_producto_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sku_code',
        ),
    ]
